version: '3.8'
#Please note: Persistent Volume has not been implemented in this compose file. All Services have been provided with service names inside app.prop file. Env variables are not provided inside app.prop. These changes are needed for finalization
services:
    adminer:
      image: adminer
      restart: always
      ports:
        - 8088:8080
# service reg 
    ecom-service-registry:
      image: parthkarad/ecom-service-registry:latest
      restart: always
      ports:
        - "8761:8761"
      environment:
        SERVER_PORT: 8761
# api gateway
    ecom-api-gateway:
      image: parthkarad/ecom-api-gateway:latest
      ports:
        - "8090:8090"
      environment:
        SERVER_PORT: 8090
      depends_on:
        - ecom-service-registry
# auth service 
    ecom-auth-service:
      image: parthkarad/ecom-auth-service:latest
      ports:
        - "9000:9000"
      environment:
        SERVER_PORT: 9000
        PGHOST : pgsql-auth
        POSTGRES_DB: algosneakers
        POSTGRES_USER: postgrestest
        POSTGRES_PASSWORD: pass@123
        PGPORT: 5432
      depends_on:
        - ecom-service-registry
        - ecom-api-gateway
        - pgsql-auth

    pgsql-auth:
      image: postgres
      ports:
        - 5400:5432
      environment:
        POSTGRES_DB: algosneakers
        POSTGRES_USER: postgrestest
        POSTGRES_PASSWORD: pass@123
        PGPORT: 5432
# order service 
    ecom-order-service:
      image: parthkarad/ecom-order-service:latest
      restart: always
      ports:
        - "8082:8082"
      environment:
        SERVER_PORT: 8082
        PGHOST : pgsql-order
        POSTGRES_DB: algosneakers
        POSTGRES_USER: postgrestest
        POSTGRES_PASSWORD: pass@123
        PGPORT: 5432
      depends_on:
        - pgsql-order
        - ecom-service-registry

    pgsql-order:
      image: postgres
      ports:
        - 5432:5432
      environment:
        POSTGRES_DB: algosneakers
        POSTGRES_USER: postgrestest
        POSTGRES_PASSWORD: pass@123
        PGPORT: 5432

# inventory service 
    ecom-inventory-service:
      image: parthkarad/ecom-inventory-service:latest
      restart: always
      ports:
        - "8092:8092"
      environment:
        # SERVER_PORT: 8092
        PGHOST : pgsql-inventory
        POSTGRES_DB: algosneakers
        POSTGRES_USER: postgrestest
        POSTGRES_PASSWORD: pass@123
        PGPORT: 5432
      depends_on:
        - pgsql-inventory
        - ecom-service-registry
        
    pgsql-inventory:
      image: postgres
      ports:
        - 5492:5432
      environment:
        POSTGRES_DB: algosneakers
        POSTGRES_USER: postgrestest
        POSTGRES_PASSWORD: pass@123
        PGPORT: 5432

# product service 
    #PRODUCT-SERVICE
    ecom-product-service:
      image: parthkarad/ecom-product-service:latest
      ports:
        - "8081:8081"
      environment:
        SERVER_PORT: 8081
        MONGODB_URL: mongodb://mongo-product:27017/product-service
      depends_on:
        - mongo-product
        - redis-product
        - ecom-service-registry

    mongo-product:
      image: mongo
      ports:
        - 27017:27017
    
    redis-product: 
      image: redis
      ports:
        - "6379:6379"
      environment:
        REDIS_DATABASES: 8
      
